version: "3.7"


services:   
  zpi-tt-client:
    image: zpitwitteranalysis.jfrog.io/zpi/zpi-twitter-client:latest
    container_name: client
    ports:
      - 3001:3001

  zpi-data-provider:
    image: zpitwitteranalysis.jfrog.io/zpi/zpi-data-provider:latest
    container_name: data-provider
    command: npm start
    working_dir: /app
    ports:
      - 3000:3000

  zpi-user-service:
    image: zpitwitteranalysis.jfrog.io/zpi/zpi-user-service:latest
    container_name: user-service
    expose:
      - 8080
    ports:
      - 8080:80

  zpi-twitt-analysis:
    image: zpitwitteranalysis.jfrog.io/zpi/zpi-analysis-service:latest
    container_name: twitt-analysis
    ports:
      - 8003:8003
